# Generated by Django 3.2.3 on 2025-01-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20250106_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('author', 'user')},
        ),
    ]
