version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: umilja/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media

  frontend:
    image: umilja/foodgram_frontend
    env_file: .env
    depends_on:
      - db
    command: cp -r /app/build/. /static/
    volumes:
      - static:/frontend_static
  gateway:
    image: umilja/foodgram_infra
    env_file: .env
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/media
    ports:
      - 8000:80