version: '3.3'

volumes:
  pg_data:
  static:
  media:
  frontend:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: umilja/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/media
    #command: >
    #  sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 foodgram_backend.wsgi:application"

  frontend:
    image: umilja/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: umilja/foodgram_infra
    env_file: .env
    depends_on:
      - db
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/media
    ports:
      - 8000:80
